hfeat: 512
embtype: codebert
embfeat: -1
num_heads: 4
lr: 0.0001
hdropout: 0.3
mlpdropout: 0.2
dropout: 0.2
methodlevel: false
nsampling: true
model: rgcn
loss: ce
multitask: linemethod
stmtweight: 1
random: false
scea: 0.5
